classdef ReplacementTextNodeAnchor < uint32
    enumeration
        North           (1)
        NorthEast       (2) 
        East            (3) 
        SouthEast       (4)
        South           (5)
        SouthWest       (6)
        West            (7) 
        NorthWest       (8)
        Base            (9)
        Center          (10)
        Mid             (11)
    end
    methods 
        function strRes = toTikz(obj)
            vals = { 
                'north'
                'north east'
                'east'
                'south east'
                'south'
                'south west'
                'west'
                'north west'
                'base'
                'center'
                'mid'
            };
            strRes = vals{obj};
        end
    end
    methods(Access = public, Static)
        function obj = fromTextProp(hStr, vStr)
            import overtikz.*
            vertIdx = containers.Map({ ...
                'bottom', ...
                'top', ...
                'middle', ...
                'baseline', ...
                }, ...
                { ...
                    3
                    1
                    2
                    2
                } ...
            );
            horizIdx = containers.Map({ ...
                'left', ...
                'center', ...
                'right', ...
                }, ...
                { ...
                    3
                    2
                    1
                } ...
            );
            if strcmp(hStr, 'center') && (strcmp(vStr, 'middle') || strcmp(vStr, 'baseline') )
                vertSel = containers.Map({ ...
                    'bottom', ...
                    'top', ...
                    'middle', ...
                    'baseline', ...
                    }, ...
                    { ...
                        ReplacementTextNodeAnchor.South, ...
                        ReplacementTextNodeAnchor.North, ...
                        ReplacementTextNodeAnchor.Mid, ...
                        ReplacementTextNodeAnchor.Base ...
                    } ...
                );
                obj = vertSel(vStr);
            else
                x = horizIdx(hStr);
                y = vertIdx(vStr);
                vertSel = {
                    ReplacementTextNodeAnchor.NorthWest, ReplacementTextNodeAnchor.North, ReplacementTextNodeAnchor.NorthEast
                    ReplacementTextNodeAnchor.West, ReplacementTextNodeAnchor.Mid, ReplacementTextNodeAnchor.East
                    ReplacementTextNodeAnchor.SouthWest, ReplacementTextNodeAnchor.South, ReplacementTextNodeAnchor.SouthEast
                };
                obj = vertSel{y, x};
            end
        end
    end
end